export const INFTS_CREDIT_SCORE_ABI = {
  address: "43e8211c2cfad783147c6f8ce36a4b561f88d9bfaf37f834e1d1c75e563e2cfb",
  name: "infts_credit_score",
  friends: [],
  exposed_functions: [
    {
      name: "mint_sbt",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "set_pending_admin",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "accept_admin",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "update_mint_fee_collector",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "update_mint_fee",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "update_score",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::object::Object<0x4::token::Token>", "u64"],
      return: [],
    },
    {
      name: "batch_update_scores",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<0x1::object::Object<0x4::token::Token>>", "vector<u64>"],
      return: [],
    },
    {
      name: "get_admin",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "get_pending_admin",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["0x1::option::Option<address>"],
    },
    {
      name: "get_mint_fee_collector",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "get_mint_fee",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
    {
      name: "get_score",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::object::Object<0x4::token::Token>"],
      return: ["u64"],
    },
    {
      name: "get_last_updated",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::object::Object<0x4::token::Token>"],
      return: ["u64"],
    },
    {
      name: "get_mint_timestamp",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::object::Object<0x4::token::Token>"],
      return: ["u64"],
    },
    {
      name: "has_minted",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "get_user_sbt",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::option::Option<0x1::object::Object<0x4::token::Token>>"],
    },
    {
      name: "get_total_minted",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
    {
      name: "get_user_score",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
  ],
  structs: [
    {
      name: "MintSbtEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "token_obj", type: "0x1::object::Object<0x4::token::Token>" },
        { name: "recipient_addr", type: "address" },
        { name: "mint_fee", type: "u64" },
        { name: "timestamp", type: "u64" },
      ],
    },
    {
      name: "UpdateScoreEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "token_obj", type: "0x1::object::Object<0x4::token::Token>" },
        { name: "old_score", type: "u64" },
        { name: "new_score", type: "u64" },
        { name: "updater", type: "address" },
        { name: "timestamp", type: "u64" },
      ],
    },
    {
      name: "AdminChangedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "old_admin", type: "address" },
        { name: "new_admin", type: "address" },
        { name: "timestamp", type: "u64" },
      ],
    },
    {
      name: "MintFeeUpdatedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "old_fee", type: "u64" },
        { name: "new_fee", type: "u64" },
        { name: "updater", type: "address" },
        { name: "timestamp", type: "u64" },
      ],
    },
    {
      name: "TokenProperties",
      is_native: false,
      is_event: false,
      abilities: ["key", "store"],
      generic_type_params: [],
      fields: [
        { name: "score", type: "u64" },
        { name: "last_updated", type: "u64" },
        { name: "mint_timestamp", type: "u64" },
      ],
    },
    {
      name: "CollectionOwnerConfig",
      is_native: false,
      is_event: false,
      abilities: ["key", "store"],
      generic_type_params: [],
      fields: [
        { name: "extend_ref", type: "0x1::object::ExtendRef" },
        { name: "collection_obj", type: "0x1::object::Object<0x4::token::Collection>" },
        { name: "token_counter", type: "u64" },
      ],
    },
    {
      name: "Config",
      is_native: false,
      is_event: false,
      abilities: ["key", "store"],
      generic_type_params: [],
      fields: [
        { name: "admin_addr", type: "address" },
        { name: "pending_admin_addr", type: "0x1::option::Option<address>" },
        { name: "mint_fee_collector_addr", type: "address" },
        { name: "mint_fee", type: "u64" },
        { name: "collection_owner_obj", type: "0x1::object::Object<43e8211c2cfad783147c6f8ce36a4b561f88d9bfaf37f834e1d1c75e563e2cfb::infts_credit_score::CollectionOwnerConfig>" },
        { name: "user_tokens", type: "0x1::table::Table<address, 0x1::object::Object<0x4::token::Token>>" },
      ],
    },
  ],
} as const;
